### ISSUE TITLE
partial overlap of a horizontal avatar list

### ISSUE THREAD

**Issue by mikem-mup** [meetup/sassquatch2#163]
it's in the redesign beta, and is something that would require a (simple) SQ2 update to support. For the member list, we would probably want all taps to send you to the full member listing view rather than trying to send you to the profile of the avatar directly under your fat finger.

![screen shot 2015-08-01 at 9 40 46 am](https://cloud.githubusercontent.com/assets/8643567/9018270/6e373746-3831-11e5-8b6a-35f4520dc546.png)

something like

```scss
.inlineblockList--overlap {
    > li {
        padding: 0;
        margin-right: -$space-half;
    }
    .avatar--person {
        border: 3px solid $C_contentBG;
    }
}
```
