### ISSUE TITLE
button--contrast

### ISSUE THREAD

**Issue by mattkime** [meetup/sassquatch2#197]
![screen shot 2015-10-21 at 5 16 46 pm](https://cloud.githubusercontent.com/assets/216176/10650481/c41db7e0-7817-11e5-8756-4aa2a1598570.png)

**Comment by akdetrick** [comment]
We're currently using transitional button styles - I don't want to create a new visual variant before we implement the S&W styles. 

We can put this in page-specific CSS like so:

```scss
.button--editPhoto { 
     @include buttonBase();
     @include color-all($C_textPrimary);
     background: $C_white;
     &:hover,
     &:active {
          background: $C_ mediumGray;
     }
}
```
